# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: judge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'judge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bjudge.proto\x12\x04GRPC\"<\n\x0cJudgeRequest\x12\x14\n\x0cstudent_code\x18\x01 \x01(\t\x12\x16\n\x0equestion_alias\x18\x02 \x01(\t\"1\n\rJudgeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"a\n\rSubmitRequest\x12\x14\n\x0cstudent_code\x18\x01 \x01(\t\x12\x16\n\x0equestion_alias\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\"1\n\x0eSubmitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2w\n\x0cJudgeService\x12\x32\n\x07Request\x12\x12.GRPC.JudgeRequest\x1a\x13.GRPC.JudgeResponse\x12\x33\n\x06Submit\x12\x13.GRPC.SubmitRequest\x1a\x14.GRPC.SubmitResponseB\x08\n\x04GRPCP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'judge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\004GRPCP\001'
  _globals['_JUDGEREQUEST']._serialized_start=21
  _globals['_JUDGEREQUEST']._serialized_end=81
  _globals['_JUDGERESPONSE']._serialized_start=83
  _globals['_JUDGERESPONSE']._serialized_end=132
  _globals['_SUBMITREQUEST']._serialized_start=134
  _globals['_SUBMITREQUEST']._serialized_end=231
  _globals['_SUBMITRESPONSE']._serialized_start=233
  _globals['_SUBMITRESPONSE']._serialized_end=282
  _globals['_JUDGESERVICE']._serialized_start=284
  _globals['_JUDGESERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
