# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import judge_pb2 as judge__pb2
import typed_judge_pb2 as typed__judge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in typed_judge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TypedJudgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTyped = channel.unary_unary(
                '/GRPC.TypedJudgeService/RequestTyped',
                request_serializer=typed__judge__pb2.TypedRequest.SerializeToString,
                response_deserializer=typed__judge__pb2.TypedData.FromString,
                _registered_method=True)
        self.SubmitTyped = channel.unary_unary(
                '/GRPC.TypedJudgeService/SubmitTyped',
                request_serializer=typed__judge__pb2.TypedAnswer.SerializeToString,
                response_deserializer=judge__pb2.SubmitResponse.FromString,
                _registered_method=True)


class TypedJudgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTyped(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTyped(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TypedJudgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTyped': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTyped,
                    request_deserializer=typed__judge__pb2.TypedRequest.FromString,
                    response_serializer=typed__judge__pb2.TypedData.SerializeToString,
            ),
            'SubmitTyped': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTyped,
                    request_deserializer=typed__judge__pb2.TypedAnswer.FromString,
                    response_serializer=judge__pb2.SubmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPC.TypedJudgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GRPC.TypedJudgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TypedJudgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTyped(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPC.TypedJudgeService/RequestTyped',
            typed__judge__pb2.TypedRequest.SerializeToString,
            typed__judge__pb2.TypedData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTyped(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPC.TypedJudgeService/SubmitTyped',
            typed__judge__pb2.TypedAnswer.SerializeToString,
            judge__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
