syntax = "proto3";
package GRPC;
option java_package = "GRPC";
option java_multiple_files = true;

service JudgeService {
  rpc Request (JudgeRequest) returns (JudgeResponse);
  rpc Submit  (SubmitRequest) returns (SubmitResponse);
}

message JudgeRequest {
  string student_code   = 1;
  string question_alias = 2;
}

message JudgeResponse {
  string request_id = 1;
  string data       = 2;
}

message SubmitRequest {
  string student_code   = 1;
  string question_alias = 2;
  string request_id     = 3;
  string answer         = 4;
}

message SubmitResponse {
  string status  = 1;
  string message = 2;
}
